### ISSUE TITLE
querySelector not working properly for attribute matches

### ISSUE THREAD

**Issue by yuri014** [svgdotjs/svgdom#103]
I have an attribute like this `clip-path="url(#ClipPath1)"` and querySelector cannot find it with `[clip-path="url(#ClipPath1)"]`.

If I remove the # from both the element and the query it works correctly.

**Comment by Fuzzyma** [comment]
fixed in (0.1.14)[https://github.com/svgdotjs/svgdom/releases/tag/0.1.14]
