### ISSUE TITLE
`window.NodeList.prototype.reduce` is `undefined`

### ISSUE THREAD

**Issue by KermanX** [svgdotjs/svgdom#105]
https://github.com/svgdotjs/svgdom/blob/cde873e869ad57d772fda593fa2a8b125fac6871/src/utils/bboxUtils.js#L46

Here `window.NodeList.prototype.reduce` is used, but AFAIK, there is no definition of it in MDN.

The issue is exposed especially when running SVGDOM with JSDOM.

**Comment by Fuzzyma** [comment]
Read the last sentence in the readme and it begins to make sense :D.

This Dom implementation is not 100% to spec. If you encountered an error, create a reproduction so I can fix the bug.
Just positing an error message doesn't help that much :D

**Comment by Fuzzyma** [comment]
You are somehow mixing 2 dom libraries and expecting it to work. It most likely wont. The bug you encounter is because jsdom expects a dom created by jsdom

**Comment by KermanX** [comment]
Thanks for your help.
I mixed two libraries because I want to use svgdom as a polyfill for running mermaid in jsdom, nodejs.
I opened this issue just wondering if it is a mistake. Since it now turned out to be not, I am closing the issue.

**Comment by KermanX** [comment]
😀
