### ISSUE TITLE
Throws error when the SVG has path element with empty d attribute.

### ISSUE THREAD

**Issue by banujan6** [svgdotjs/svgdom#116]
I am working on manipulating SVG on the Service Side with `node` + `svgdom` + `svgjs`. The SVG is generated from PDF using `pdf2svg`. The generated SVGs often have `path` tags with empty `d` attributes.

```html
<path style="stroke:none;" d=""/>
```
So, parsing such SVG throws the following error:
```
webpack://svgdom/./src/utils/pathUtils.js:131
      pathHandlers[s].call(null,
^
TypeError: Cannot read properties of undefined (reading 'call')
    at pathParser (webpack://svgdom/./src/utils/pathUtils.js:131:1)
    at Module.getPathSegments (webpack://svgdom/./src/utils/pathUtils.js:639:1)
    at getPathSegments (webpack://svgdom/./src/utils/bboxUtils.js:62:12)
    at getSegments (webpack://svgdom/./src/utils/bboxUtils.js:16:1)
    at webpack://svgdom/./src/utils/bboxUtils.js:48:1
    at Array.reduce (<anonymous>)
    at getPathSegments (webpack://svgdom/./src/utils/bboxUtils.js:46:1)
    at getSegments (webpack://svgdom/./src/utils/bboxUtils.js:16:1)
    at webpack://svgdom/./src/utils/bboxUtils.js:48:1
    at Array.reduce (<anonymous>)
```

### Code Sample

```javascript
import { SVG } from '@svgdotjs/svg.js';
const { createSVGWindow } = require('svgdom');

global.window = createSVGWindow();
global.document = global.window.document;

// register window and document
registerWindow(window, document);

const canvas = SVG( svgString );
```

**Works Fine**
```html
<symbol overflow="visible" id="glyph1-1">
      <path style="stroke:none;" d="M 8.84375 -0.203125 L 7.8125 0.828125 L 6.53125 -0.453125 C 5.914062 -0.078125 5.207031 0.109375 4.40625 0.109375 C 3.269531 0.109375 2.328125 -0.242188 1.578125 -0.953125 C 0.828125 -1.671875 0.453125 -2.5625 0.453125 -3.625 C 0.453125 -4.695312 0.828125 -5.585938 1.578125 -6.296875 C 2.328125 -7.003906 3.269531 -7.359375 4.40625 -7.359375 C 5.519531 -7.359375 6.453125 -7.003906 7.203125 -6.296875 C 7.960938 -5.585938 8.34375 -4.695312 8.34375 -3.625 C 8.34375 -2.8125 8.101562 -2.082031 7.625 -1.4375 Z M 2.859375 -2.046875 C 3.265625 -1.640625 3.773438 -1.4375 4.390625 -1.4375 C 5.015625 -1.4375 5.523438 -1.640625 5.921875 -2.046875 C 6.328125 -2.460938 6.53125 -2.988281 6.53125 -3.625 C 6.53125 -4.269531 6.328125 -4.796875 5.921875 -5.203125 C 5.523438 -5.617188 5.015625 -5.828125 4.390625 -5.828125 C 3.773438 -5.828125 3.265625 -5.617188 2.859375 -5.203125 C 2.453125 -4.796875 2.25 -4.269531 2.25 -3.625 C 2.25 -2.988281 2.453125 -2.460938 2.859375 -2.046875 Z M 2.859375 -2.046875 "/>
</symbol>
```

**Not Working**
```html
<symbol overflow="visible" id="glyph1-0">
     <path style="stroke:none;" d=""/>
</symbol>
```

### Environment
`NodeJS v19.7.0`, `@svgdotjs/svg.js ^3.1.2`, `MacOS Ventura - M1`

**Comment by banujan6** [comment]
## Temp Fix
I have added a temporary fix in the `utils/pathUtils.js` file. i simply wrapped it with an if condition.
```javascript
if (pathHandlers[s]) {
   arr.push(
       pathHandlers[s].call(null,
          array.slice(index, (index = index + paramCnt[s.toUpperCase()])).map(parseFloat),
          p, r, p0,
          isBeziere(arr[arr.length - 1])
       )
   )
}
```

The above change resolves the issue and gives the expected output. But I am not sure If it causes any other side effects in any other scenario. Update here if it is a valid fix so I can send the PR.

**Comment by Fuzzyma** [comment]
I cannot reproduce this issue on my machine. Can you try updating your svg.js version?

**Comment by banujan6** [comment]
I am using the latest version of `svg.js` -> `"version": "3.2.0",`. I have attached the SVG I used.

![SVG File](https://github.com/svgdotjs/svgdom/assets/24388013/7ac5f57e-f4f9-4ad5-a601-02da6f83987b)

**Comment by banujan6** [comment]
In my case, I get `undefined` for the `array` parameter for those `path`s.
```javascript
const pathParser = (array) => {...}
```

I added a condition as below:
```javascript
const pathParser = (array) => {

  // If the array is undefined just return empty array.
  if ( !array ) {
    return [];
  }

  // prepare for parsing
  const paramCnt = { M: 2, L: 2, H: 1, V: 1, C: 6, S: 4, Q: 4, T: 2, A: 7, Z: 0 }
```

Now it solves the problem for now.

**Comment by Fuzzyma** [comment]
Your code sample looks a bit off. How does this work?

```js
import { SVG } from '@svgdotjs/svg.js';
const { createSVGWindow } = require('svgdom');

// register window and document
registerWindow(window, document); // <-- you register window and document before you even created it

global.window = createSVGWindow(); // <-- this should go above
global.document = global.window.document;

const canvas = SVG( svgString );
```

This shouldntw work at all... (unless you are running this code in a browser where window and document are defined)

I trid your example and it just runs like normal. No errors are thrown. A

**Comment by banujan6** [comment]
@Fuzzyma My bad. I cleaned up some other code to provide a clean example, I messed up with the order. However, In my original code, it is in the correct order. Also works fine for SVGs except for this specific scenario.

**Comment by Fuzzyma** [comment]
Really weird. The thing is I totally expect this to be a bug but it just doesnt happen in my code so I assume I just have bug in my example to reproduce your bug lol.

**Comment by banujan6** [comment]
I understand. I do a lot of manipulation on SVG, Let me narrow it down. May be I am doing something wrong.

**Comment by banujan6** [comment]
@Fuzzyma It happens here `bbox = itemCanvas.node.getBBox();`.

The `itemCanvas` is an `SVG` object and `topGroupElement` is a high-level group element.
```javascript
for (let item of topGroupElement.children ) {
     const itemCanvas = SVG();
     const group = itemCanvas.group();
     
     // Doing a lot of transformation for each type of element path / use / g / etc..
     //After all, append the item to the newly created canvas.
     group.add( item as any );

    // recalculate the bbox, This is where the error occurs if the path exist without d values
     const bbox = itemCanvas.node.getBBox();
}
```

**Comment by banujan6** [comment]
Yeah I am sorry. It happens when calculating the bbox. The reason we create SVG element for each item, Coz we want to isolate each item in `svg` to our internal format. So,
```
<defs>
   <symbol xmlns="http://www.w3.org/2000/svg" overflow="visible" id="glyph0-0">
      <path style="stroke:none;" d=""/>
   </symbol>
</defs>
<g>
    <use xlink:href="#glyph0-0">
<g>
```
Need to be converted to,
```
<svg>
   <g>
       <path style="stroke:none;" d=""/>
   </g>
</svg>
```

After the conversion, when calculating the `bbox` only I get the above error.

**Comment by banujan6** [comment]
@Fuzzyma I fixed it from my side. I checked the `d` value of the element and if it was empty, I skipped it from adding it to canvas. It does the job. I am okay with closing this issue.

If you feel like this no need to be fixed / not a bug a all. You can close this issue. Thanks for your time and support. :)

**Comment by Fuzzyma** [comment]
it definitely needs to be fixed so I will leave that open :). Thanks for reporting!
