### ISSUE TITLE
How to "clean up" the element

### ISSUE THREAD

**Issue by klemensz** [svgdotjs/svgdom#12]
Hi,
What is the suggested way to empty the `document.documentElement` to start over with a clean SVG element?
Right now my solution is to `document.createElement('svg')`, then create the SVG with it, and then do `document.removeChild(element)`. Or is there a better solution? By just using re-using document.documentElement the old SVG image will stay there.
Thanks

**Comment by Fuzzyma** [comment]
There is none. In future versions you will be able to just create a new window with

```js
svgdomConstructor = require('svgdom')

window = new svgdomConstructor()
```

or something like that.
For now yours is the way to you

**Comment by klemensz** [comment]
Example:

```
        let element = document.createElement('svg');
        var draw = SVG(element).size(WIDTH, HEIGHT);
```
do some drawing, then...
```
        const svgString = draw.svg();
        document.removeChild(element);
```

**Comment by Neonit** [comment]
But why do you call `document.removeChild(element)` in the end? You never added the element to the document, e.g. by calling `document.appendChild(element)`. `document.createElement` does not automatically add the created element as child to the document. It creates a new, independent element, which is not yet anywhere in the DOM tree. I also fiddled around and `element.parentNode` is `undefined` right before calling `removeChild` in the example code.

**Comment by Fuzzyma** [comment]
You are right. It is unnecessary here.

**Comment by Fuzzyma** [comment]
This is now solved
