### ISSUE TITLE
How to export animated svg.

### ISSUE THREAD

**Issue by liudonghua123** [svgdotjs/svgdom#124]
Hi, I tried to rewrite [readme-typing-svg](https://github.com/DenverCoder1/readme-typing-svg)/[readme-typing-svg.demolab.com](https://readme-typing-svg.demolab.com/demo/) using pure front-end js. And I am not familar with svg and I used some code generated via GP4o. The main code is [lib.ts](https://github.com/liudonghua123/readme-typing-svg-ts/blob/main/src/lib.ts) and [App.vue](https://github.com/liudonghua123/readme-typing-svg-ts/blob/main/src/App.vue).

If I insert the [svg element](https://liudonghua123.github.io/readme-typing-svg-ts/) in the preview div, it's ok. But when I export svg string, it is like this.

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="435" height="500" viewBox="0 0 435 500">
    <rect width="435" height="500" fill="#00000000"></rect><text font-size="24" fill="#36BCF7FF" font-weight="400" font-family="Fira Code" letterSpacing="normal" x="10" y="238">
        <tspan dy="0" x="10">T</tspan>
    </text><text font-size="24" fill="#36BCF7FF" font-weight="400" font-family="Fira Code" letterSpacing="normal">
        <tspan dy="0" x="0">|</tspan>
    </text>
</svg>
```

What I expected is like [readme-typing-svg.demolab.com](https://readme-typing-svg.demolab.com/demo/) exported svg.

```svg
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 435 50' style='background-color: #00000000;' width='435px' height='50px'>
    <path id='path0'>
        <!-- Single line -->
        <animate id='d0' attributeName='d' begin='0s;d0.end' dur='6000ms' fill='remove' values='m0,25 h0 ; m0,25 h435 ; m0,25 h435 ; m0,25 h0' keyTimes='0;0.66666666666667;0.83333333333333;1' />
    </path>
    <text font-family='"Fira Code", monospace' fill='#36BCF7' font-size='20' dominant-baseline='auto' x='0%' text-anchor='start' letter-spacing='normal'>
        <textPath xlink:href='#path0'>
            The five boxing wizards jump quickly
        </textPath>
    </text>
</svg>
```

The main code of svg generation of [readme-typing-svg](https://github.com/DenverCoder1/readme-typing-svg) is [main.php](https://github.com/DenverCoder1/readme-typing-svg/blob/main/src/templates/main.php) and [RendererView.php](https://github.com/DenverCoder1/readme-typing-svg/blob/main/src/views/RendererView.php).

**Comment by Fuzzyma** [comment]
You never add an animate-element to the svg. So there is no way it will show up in the exported svg.
Your animation is done through js and not through svg. So you would need to include the script in your svg.

However, this is clearly not a bug. Please ask questions like this on stackoverflow

**Comment by liudonghua123** [comment]
@Fuzzyma Thanks, I rewrite the svg creation using raw plain string concatation now. See the [code ](https://github.com/liudonghua123/readme-typing-svg-ts/blob/main/src/lib.ts).

**Comment by Fuzzyma** [comment]
Perfect! Probably fits your problem space better!
