### ISSUE TITLE
Mysterious inner svg with polyline.

### ISSUE THREAD

**Issue by YuriGor** [svgdotjs/svgdom#13]
Hi! 
I have same code for browser and for nodejs, and generated svg string differs badly.
When I do it at node, SVG contains excessive inner svg element with polyline, which supposed to be invisible.
But graphicsmagic doesn't agree to work with such things.
My code for Node:

```
const window   = require('svgdom');
  const SVG      = require('svg.js')(window);
  const document = window.document;

let draw = SVG(document.documentElement);
//Do nothing! Or draw something - doesn't matter
console.log(draw.svg());
```
Output SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs">
<defs id="SvgjsDefs1001"></defs>
<svg id="SvgjsSvg1002" width="2" height="0" style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0">
<polyline id="SvgjsPolyline1003" points="0,0"></polyline>
<path id="SvgjsPath1004" d="M0 0 "></path></svg></svg>
```
gm says when seeing this:

> Error: gm compare: Non-conforming drawing primitive definition (polyline).

**Comment by YuriGor** [comment]
As I see in the sources of svg.js, this
[hidden poly was made intentially](https://github.com/svgdotjs/svg.js/blob/e62d38e60f4cf06439df9ed828e3310162c66e24/src/svg.js#L138)
May be in case of svgdom some cleanup code was not called?
Can I do it manually as a workaround?

**Comment by Fuzzyma** [comment]
The problem is, that svg.js uses this hidden svg to calculate a bunch of stuff. The code to calculate these things by hand would be bloating the lib and the rather slow.
In case of svgdom this is not needed of because the code to calculate all these things are present somehow Anyway. But svg.js is not aware of this extra methods. It still tries to just call the methods on the extra element. If it's not there it will break.
We tried to remove the - as we call it - parser but it's not that easy. Especially the classes which are not bound to any instances need it to generate a native svg matrix or svgpoint. Furthermore path bounding boxes are not easily calculated by hand.

You see there are reasons why this little bit of extra svg has to stay for now.
but svgdom works like a Dom. You can just remove it by hand before exporting

**Comment by YuriGor** [comment]
Could you please provide an example how to remove it with svgjs api?
Or I should pars output string by my self with regex?

**Comment by Fuzzyma** [comment]
You can do it easily with svg.js with select('svg').remove() or by using normal Dom api. removeChild. You can pass a css selector to select to get the svg you want to remove

**Comment by YuriGor** [comment]
If I'll remove this hidden element from DOM-tree, will svg.js stop to work? 
If I need to draw something, export svg, draw some more, export again..

How do you think, if I'll add some clean-up code to the svg() method, which will remove this element from the svg string right before returning from svg() method - will this pull request be accepted int svg.js project?

**Comment by Fuzzyma** [comment]
we might remove it, export and add it back. You need to know, that svg.js holds a reference to that special object. So you cant just create a new one.
Furthermore in the browser this "extra" svg does not redies in the main svg but in the body. So there is no need to add remove it in this case

**Comment by Fuzzyma** [comment]
PS: svg.js version 3.0 does ONLY add the extra svg if it is needed at any point of the code

**Comment by YuriGor** [comment]
I tried to do
`document.querySelectorAll('polyline[points="0,0"]').parentElement.remove();`
and
`document.querySelectorAll('polyline[points="0,0"]').parentElement.remove();`
but it does not work:

> TypeError: Cannot read property 'remove' of undefined

**Comment by Fuzzyma** [comment]
I said: either use `select(cssselector).remove()` OR use dom methods. Mixing up both ofc does not work.
What you want is rather this:

```js
rootSVG.select('polyline[points="0,0"]').parent().remove()
```

**Comment by YuriGor** [comment]
Ok, thank you, as said above, I finally deleted DOM Node successfully by moving from polyline up to gran-parent and calling removeChild with inner svg elemnt as argument

**Comment by YuriGor** [comment]
I did it like this (not for defs):
```
const window = require('svgdom');
const SVG = require('svg.js')(window);
const document = window.document;
let svgEl = document.createElement('div');
document.documentElement.appendChild(svgEl);
let draw = SVG(svgEl).size(size.width, size.height);
draw.rect(size.width, size.height).fill('#fff');
draw.select('polyline[points="0,0"]').parent().remove();
let str = draw.svg();
```

**Comment by Fuzzyma** [comment]
@simonseddon the way of @YuriGor is the correct way. The lines which are important here are:

```js
draw.select('polyline[points="0,0"]').parent().remove();
let str = draw.svg();
```

This will simply remove the extra svg in your output
