### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by JoshuaWalsh** [svgdotjs/svgdom#15]
I'm using svgdom to run svg.js on NodeJS v8.7.0. I'm using `svg.select("[id^=my]")` and getting the following error:

> message: "Cannot read property 'startsWith' of null"
> stack: "TypeError: Cannot read property 'startsWith' of null
>     at create.^= (c:\git\data-import-scripts\node_modules\svgdom\class\CssQuery.js:171:60)
>     at create.matches (c:\git\data-import-scripts\node_modules\svgdom\class\CssQuery.js:262:27)
>     at create.matchHelper (c:\git\data-import-scripts\node_modules\svgdom\class\CssQuery.js:99:37)
>     at create.matches (c:\git\data-import-scripts\node_modules\svgdom\class\CssQuery.js:92:17)
>     at create.matches (c:\git\data-import-scripts\node_modules\svgdom\class\Node.js:369:34)
>     at create.querySelectorAll (c:\git\data-import-scripts\node_modules\svgdom\class\Node.js:374:31)
>     at create.querySelectorAll (c:\git\data-import-scripts\node_modules\svgdom\class\Node.js:375:45)
>     at create.querySelectorAll (c:\git\data-import-scripts\node_modules\svgdom\class\Node.js:375:45)
>     at Function.SVG.select (c:\git\data-import-scripts\node_modules\svg.js\dist\svg.js:5322:40)
>     at create.select (c:\git\data-import-scripts\node_modules\svg.js\dist\svg.js:5331:16)"

I believe the reason I'm getting this error is because not every element in my SVG document has an id. I stepped through the execution and found that the attributeMatcher for "^=" is being called with i=false, a="my" and b=null.

**Comment by YMIndustries** [comment]
I've temporarily patched the issue on my end by changing 

    if(!this.attrs[i].matcher(node.getAttribute(this.attrs[i].name)))

to

    if(!this.attrs[i].matcher(node.getAttribute(this.attrs[i].name) || ""))

This is a bit inelegant, but it works for my purposes.

**Comment by apla** [comment]
I've added similar solution in the pull request #16 commit 9671b35

**Comment by Partho99** [comment]
fesdf
