### ISSUE TITLE
Load an SVG file and use it with svg.js

### ISSUE THREAD

**Issue by Jordan4jc** [svgdotjs/svgdom#17]
This looks like where I need to be, but I'm having trouble figuring this one out.

I have an SVG file on my server that I want to be able to edit the text in and then return a temporary PNG for instance to create a PDF

Once I get to the editing an SVG I should be able to finish the rest.

I was able to grab the DOM elements out of the SVG with `fs.readFile`, but how do I turn this into an SVG I can make edits to with `svg.js`?

**Comment by Fuzzyma** [comment]
When you want to use svg.js on the server, take a look into svgdom.
When you don't plan to do that on the server you can just create a new SVG-instance and use the import function (`svgdoc.svg(svgstring)`)

**Comment by Jordan4jc** [comment]
Right so I'm using this one the server and have installed `svgdom`, I see that the `svgdom` import returns a `window` object that I can pass into `svg.js`?

If I follow this setup how do I get my code from the svg file I loaded into the `svgdom` so I can start working with it?

**Comment by Fuzzyma** [comment]
The example in the Readme is pretty clear about how you setup svgdom with svg.js. After you got your instance, you can use the svg-method to import your svg string. Note that your imported svg is in a nested svg in the document. You can search for your svg instance by ID or similar (try svg.select(css Selector)).

**Comment by Jordan4jc** [comment]
I'm having a hard time with this one I'm sorry. Maybe I'm not really understanding what you're saying

```
const window = require('svgdom')
const SVG = require('svg.js')(window);
const fs = require('fs');
const tag = fs.readFileSync(`images/name-tag-1-with-name.svg`,'utf8');
const draw = SVG(tag)
```
My svg loaded from the file looks like this

```
<svg id="name-tag" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 216 288">
  <defs>
    <style>
      .cls-1,
      .cls-2 {
        fill: #414042;
      }

      .cls-2 {
        opacity: 0.95;
      }

      .cls-3,
      .first-name,
      .last-name {
        fill: #fff;
      }

      .cls-4 {
        fill: none;
        stroke: #fff;
        stroke-miterlimit: 10;
      }

      .first-name,
      .last-name {
        font-size: 30.87px;
        font-family: Gibson-SemiBold, Gibson;
        font-weight: 700;
      }

      .cls-6 {
        letter-spacing: -0.01em;
      }

      .last-name {
        letter-spacing: -0.01em;
      }

      .cls-8 {
        letter-spacing: 0em;
      }
    </style>
  </defs>
  <title>name-tag-1-with-name</title>
  <g id="Layer_1-2" data-name="Layer 1">
    <polygon class="cls-1" points="0 0 0 288 216 0 0 0" />
    <polygon class="cls-2" points="0 288 216 288 216 0 0 288" />
    <polygon class="cls-3" points="119.35 66.27 109.12 17.38 98.95 66.02 72.4 85.51 72.4 101.58 72.41 101.61 109 74.78 145.5 101.58 145.5 85.45 119.35 66.27"
    />
    <polygon class="cls-3" points="109 82.28 108.97 82.25 72.4 109.08 72.4 125.15 72.41 125.19 109 98.37 145.5 125.15 145.5 109.04 109 82.25 109 82.28"
    />
    <polygon class="cls-3" points="109 105.85 108.97 105.83 72.4 132.66 72.4 148.75 72.41 148.77 109 121.95 145.5 148.75 145.5 132.63 109 105.83 109 105.85"
    />
    <line class="cls-4" x1="11.95" y1="183" x2="206.53" y2="183" />
    <text class="first-name" transform="translate(76.22 228.16)">
      First
    </text>
    <text class="last-name" transform="translate(47.47 266.32)">
      Last
    </text>
  </g>
</svg>
```

The error I'm getting is 

```
if (element.nodeName == 'svg') {
                  ^

TypeError: Cannot read property 'nodeName' of null
```

**Comment by Fuzzyma** [comment]
```
const window = require('svgdom') const SVG = require('svg.js')(window) const document = window.document // create svg.js instance const var draw = SVG(document.documentElement)
draw.svg(svgstring)
```

**Comment by Jordan4jc** [comment]
Okay it looks like this works, thank you

**Comment by heruan** [comment]
The workaround works, but having the `svg` nested is cumbersome. In my opinion it would be an excellent feature to be able to initialize the SVG DOM from an existing file/markup.

**Comment by Fuzzyma** [comment]
I am aware of that issue. This feature is available in svg.js 3.0 which is not yet released (and does not work with svgdom as is). Mich work ahead of. Unfortunately I don't have the time to do that atm. So you need to take that route for now

**Comment by vivekkhurana** [comment]
Any update on this? Is svgdom working with svg3.0 ?

**Comment by Fuzzyma** [comment]
Yes, it is (quite awesome as I might say ^^)

**Comment by Shadercloud** [comment]
So how do you import your own SVG without it being a nested SVG?  Or you still have to nest it even in 3.0?

**Comment by badjano** [comment]
I'm loading multiple svg files, how do I clean dom after done with an svg?

**Comment by badjano** [comment]
nevermind, svg.clear() worked for me
