### ISSUE TITLE
Gl-Matrix reference requires window

### ISSUE THREAD

**Issue by CTech-MitchM** [svgdotjs/svgdom#19]
gl-matrix.js:38 references window and throws an undefined error when trying to use this with Node:

const temp = require('svgdom');

Is this due to a gl-matrix update, and if so what version should I be using?

**Comment by pasih** [comment]
gl-matrix 2.5.1 works. I haven't had time to investigate what broke in the last gl-matrix update (i.e. whether this was "intentional" or just a side effect of something they did).

**Comment by Fuzzyma** [comment]
I added the dependency when it was version 2.3.2. Normally you do nothing wrong by allowing minor updates. I am pretty sure that has to be a bug on their side. I will open an issue for clarification.

**Comment by Fuzzyma** [comment]
See https://github.com/toji/gl-matrix/issues/310
