### ISSUE TITLE
Getting text bboxes

### ISSUE THREAD

**Issue by alexerhardt** [svgdotjs/svgdom#2]
Hi,

First of all, I cannot thank you guys enough for both this library and SVG.js - they are truly outstanding.

However, I have small issue with svgdom. You mention in your documentation that text bboxes are not yet implemented, and unfortunately this feature is crucial for our project.

I can imagine you're busy people, and we can't rely on you developing the feature, so I'm hoping you can at least offer me a few pointers on how to get around it...

Like you mention in your docs, I've tried parsing the font file, and from there I've computed a "theoretical" or "scaled" value based on yMin, yMax and the units per em. However, I can never arrive at the same figure as Chrome (and the difference is significant +10% pixels)...

Are there any pointers you could offer on how to get around this issue? Do you have any idea of how the different browsers compute this, or could you point me to any relevant snippets of code, documentation, or potential ways of solving this?

Again, thanks a lot for your time.

Cheers,
Alex

Update: I'm adding a shout-out to @Fuzzyma who I see is a svg.js contributor and very knowledgeable in headless SVGs... I also found that you asked a similar question on SO recently (http://stackoverflow.com/questions/43140096/reproduce-bounding-box-of-text-in-browsers) so maybe you can report your findings or at the very least benefit from this discussion. Thanks!!

**Comment by Fuzzyma** [comment]
Funny that you ask. I never stopped developing and managed to get text bbox working yesterday. Unfortunately my Internet is not yet connected so I can't push until Tuesday. 
If you want to know how the calculation works look into the textutils.js (when it's pushed). I admit that's a bit odd and I truly don't know if I catches all edge cases. For the fonts I tested I got 100% chrome behavior. And so I hope I catched everything

**Comment by Fuzzyma** [comment]
Lucky - just had internet and pushed the recent changes. This is released under 0.0.7 in npm

**Comment by alexerhardt** [comment]
Thank you so much Matthias!! I'll only be able to check the code this evening, but I will take a good look and play with it - will let you know if anything comes up.

**Comment by Fuzzyma** [comment]
Cool great!
