### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by jdthorpe** [svgdotjs/svgdom#20]
When I install the current versions of `svg.js` and `svgdom` like so:

     ~/temp > mkdir svg.js-test
     ~/temp > cd svg.js-test/
     ~/temp/svg.js-test > npm init
     [usual stuff here]
     ~/temp/svg.js-test > npm i svg.js svgdom
    npm notice created a lockfile as package-lock.json. You should commit this file.
    npm WARN svg.js-test@1.0.0 No description
    npm WARN svg.js-test@1.0.0 No repository field.

    + svg.js@2.6.5
    + svgdom@0.0.15
    added 79 packages from 170 contributors and audited 318 packages in 10.501s
    found 0 vulnerabilities

     ~/temp/svg.js-test > node -v
    v9.5.0

and then try the example, the first line fails like so: 

    ~/temp/svg.js-test/ > node
    > const window = require('svgdom')
    ReferenceError: window is not defined
        at Object.<anonymous> (/Users/jasonthorpe/temp/svg.js-test/node_modules/core-js/library/modules/_global.js:2:14)
        at Module._compile (module.js:660:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Module.require (module.js:604:17)
        at require (internal/module.js:11:18)

That error is fixed by using `var` instead of const, but then the second line throws an error:

     ~/temp/svg.js-test > node
    > var window = require('svgdom')
    undefined
    > const SVG      = require('svg.js')(window)
    TypeError: element.appendChild is not a function
        at new create (/Users/jasonthorpe/temp/svg.js-test/node_modules/svg.js/dist/svg.js:3618:17)
        at SVG.SVG (/Users/jasonthorpe/temp/svg.js-test/node_modules/svg.js/dist/svg.js:27:15)
    > SVG
    ReferenceError: SVG is not defined

Now if the first two `const` tokens are converted to `var`, the second line still throws an error, but the rest of the readme still works with the exception that `draw.node.outerHtml` is `undefined`, whereas the readme would suggest that this should be the same as `draw.svg()`

for what it's worth, I put the `package-loc.json` file generated by the `npm i svgdom svg.js` call [in this gist](https://gist.github.com/jdthorpe/0f7a89fe59c680a839fb42dd196816b6).

**Comment by Fuzzyma** [comment]
I never tried this libs in the interactive node shell. You might want to put your code into a js file and execue that.

**Comment by Sofness** [comment]
I'm running into the same problem

Undefined at draw.node.outerHtml for the console.log . Isn't that a library to display headless ?

**Comment by Fuzzyma** [comment]
Well - headless is not the same as running it in an interactive shell. The interactive shell has some pitfalls which you dont have in a node script. Sure you can use it in node. But please use files and not the interactive shell.

If this is not the problem, we have to dig deeper. You can also try to debug it. The code is reall straightforward

**Comment by Sofness** [comment]
Hey, thanks for that rep . I have to see before if i got that main library purpose . Is the normal behavior is to display a window  in order to have a environnement like a navigator to draw inside ?

So in fact the code normally display a yellow square at the execution ? I think i getting it wrong .

I did not use interactive shell and run into the same truble as jdthorpe . But get the same final strange result and the same undefined value for outerHtml

Lemme know :)

**Comment by Fuzzyma** [comment]
The undefined outerHTML is explained relativey easily. Its a type :D. 
In the example code it says outerHtml while outerHTML is correct. Will fix that. Any other errors?
