### ISSUE TITLE
Error while trying to load fonts

### ISSUE THREAD

**Issue by sarperdag** [svgdotjs/svgdom#22]
Hello,

First of all, thanks for this great addition to svg.js

Have been fiddling with svgdom for a couple days and I keep getting an error while I'm trying to preload my fonts. I'm sure the path is correct. 

Here is my code:

```
const window = require('svgdom')
const path = require('path');
	
var pathToFonts = path.join(__dirname, "/fonts");

console.log(pathToFonts);

window.setFontDir(pathToFonts)
.setFontFamilyMappings(
	{'Bebas': 'BEBAS.TTF'}
);
```

And here's the error:

```
path.js:28
throw new TypeError('Path must be a string. Received ' + inspect(path));
TypeError: Path must be a string. Received undefined
```

When I remove the line 

```
.setFontFamilyMappings(
	{'Bebas': 'BEBAS.TTF'}
);
```

the error goes away, but of course, the fonts aren't loaded either... 

What might be wrong here?

**Comment by Fuzzyma** [comment]
At first sight I cannot see a mistake on your side. Did you try to debug this? I think there is an error in the lazy loading part of the font. A full stacktrace would help.

As a quickfix you can try to use `preloadFonts()` which loads the fonts directly and omits the lazy loading.
