### ISSUE TITLE
Could not load font file (text bbox)

### ISSUE THREAD

**Issue by alexerhardt** [svgdotjs/svgdom#3]
Hi @Fuzzyma and team,

Been trying this since yesterday, but no luck. I've loaded 5 fonts on my server, and added their mappings and dir path as per the docs, but I get the following error:

> Could not load font file for Pacifico.Error: ENOENT: no such file or directory, open '/absolute/path/to/fonts/OpenSans-Regular.ttf'

Relevant snippets of code:

```
const window = require('svgdom');
const SVG = require('svg.js')(window);
const document = window.document;
const path = require('path');

const fontMap = {
  'Pacifico': 'Pacifico-Regular.ttf',
  'Droid Sans': 'DroidSans-Bold.ttf',
  'Rubik': 'Rubik-Black.ttf',
  'Eczar': 'Eczar-Bold.ttf',
  'Russo One': 'RussoOne-Regular.ttf'
};
var pathToFonts = path.join(__dirname, "/fonts");
window.setFontDir(pathToFonts)
.setFontFamilyMappings(fontMap);
```
I've also printed the contents of the window object in case it helps anyone:

```
     _preloaded: {},
     fontDir: '/absolute/path/to/fonts',
     fontFamilyMappings: 
      { Pacifico: 'Pacifico-Regular.ttf',
        'Droid Sans': 'DroidSans-Bold.ttf',
        Rubik: 'Rubik-Black.ttf',
        Eczar: 'Eczar-Bold.ttf',
        'Russo One': 'RussoOne-Regular.ttf' } },
```
Am I doing something wrong?

Thanks a lot for your help, again.

Cheers,
Alex

**Comment by Fuzzyma** [comment]
Mh that's odd. Try the following points:

- try preloading the fonts and report back if this works
- are the access rights to the directory set correctly? 
- try using a relative path to the font dir (avoid the magic __dir) e.g. `./fonts`

**Comment by Fuzzyma** [comment]
@alexerhardt pls try again with current master (`npm install git+https://github.com/svgdotjs/svg.js.git`).
As soon as confirmed I will release this fix under 0.0.9

**Comment by alexerhardt** [comment]
Hi,

Still no luck.

I've tried the following, as suggested:

- Updated to 0.0.8
- Tested folder/file permissions with fs.openSync, fs.readdirSync, fs.readFileSync; I can access the folder and read font file contents without a problem.
- Tried preloading

Furthermore I've tried the following:

- Added OpenSans-Regular.ttf to my fonts folder. Result: the error disappears! I tried this in the first place because even when trying to load other fonts, the error above stated it couldn't find this one.
- However, after drawing text (I've also tested a text def), like so:
  
```
  var font = 'Open Sans'; // tested other fonts, too
  var text = draw.plain(name)
                 .attr('font-family', font)
                 .attr('font-size', '100px');
```
And then checking the bbox content:

`  console.log('text bbox: ' + JSON.stringify(text.bbox()));`

Produces:

`text bbox: {"w":null,"h":null,"x2":null,"y2":null,"cx":null,"cy":null,"x":0,"y":null,"width":null,"height":null}`

I'm going to try to run this on the debugger and check things step-by-step - though I'm not entirely confident I'll be able to make sense of what's going on...

If there's anything else you'd like me to test do let me know.

Cheers,
Alex

**Comment by Fuzzyma** [comment]
Yes please try again with the current master (not 0.0.8) - see my last post :). I fixed something - it might help

**Comment by alexerhardt** [comment]
Sorry - just tried that and same results.

I was working with draw.plain() but I've also tested draw.text() and no change unfortunately.

**Comment by Fuzzyma** [comment]
I just tried again and this was working for me:

```js
const window = require('svgdom');
const SVG = require('svg.js')(window);
const document = window.document;

// maybe dont use path to join the relative path?
window.setFontDir('./fonts').setFontFamilyMappings({
  'Calibri2': 'calibri.ttf',
  'Arial2': 'arial.ttf',
  'Comic2': 'comic.ttf',
  'Coop2': 'COOPBL.TTF',
  'Finale2': 'FinaleCopyistText.ttf',
  'Free2': 'FREESCPT.TTF',
  'Georgia2': 'georgia.ttf'
})//.preloadFonts() // works both


var draw = SVG(document.documentElement).size(100,100)
console.log(draw.text('Heiasdsad').font('family', 'Comic2').size(100).bbox())
```

I have windoww, though - maybe thats a difference? Also I use node 6.10

**Comment by Fuzzyma** [comment]
You can also join the new gitter channel for better support: https://gitter.im/svgdotjs/svg.js

**Comment by alexerhardt** [comment]
Found it!!!

Ran your code exactly as you did and got it to work (also running node 6.10, but on Xubuntu)

The problem lies in using the .attr() method to set attributes. So the following **doesn't** work.

```
  var text = draw.text('blablabla')
                 .attr('font-family', 'Comic2') 
                 .attr('font-size', DEFAULT_FONTSIZE + 'px');

// ... create a bbox
```

But this does:

```
  var text = draw.text('blablabla')
                 .font('family', 'Comic2') // tested other fonts too
                 .size(100);

// ... create a bbox
```

Joining paths with __dir and all other things do not seem to pose problems. Will keep testing these but this should be more than enough to keep working. See you on Gitter - thanks!!!

**Comment by Fuzzyma** [comment]
`.attr('font-size', DEFAULT_FONTSIZE + 'px');` <-- dont use px. Its enough to write `.attr('font-size', DEFAULT_FONTSIZE);`. Maybe thats the error.
