### ISSUE TITLE
Bug in recursively getting attributes

### ISSUE THREAD

**Issue by valentinradu** [svgdotjs/svgdom#38]
I think this specific line:
https://github.com/svgdotjs/svgdom/blob/master/dom.js#L305
should actually be `&& node.nodeType === 1` since otherwise at the top of the hierarchy `node.parentNode` will be null and trying to get `nodeType` will raise.

**Comment by Fuzzyma** [comment]
Nice catch! I think you are right. Can you create a PR?

**Comment by valentinradu** [comment]
@Fuzzyma PR here: https://github.com/svgdotjs/svgdom/pull/39

**Comment by Fuzzyma** [comment]
merged and released as 0.0.19. Thanks!
