### ISSUE TITLE
TypeError: Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by gfaraj** [svgdotjs/svgdom#46]
Hello,

I'm getting an error when calling the svg function to load an svg file (using svg.js 3.0):

```
const window = require('svgdom');
const document = window.document;
const {SVG, registerWindow} = require('@svgdotjs/svg.js');
registerWindow(window , document);
let data = fs.readFileSync(filePath, 'utf8');
let element = document.createElement('svg');
const canvas = SVG(element);
canvas.svg(data);

```

In svgdom/class/Node.js:
![image](https://user-images.githubusercontent.com/2772908/66172673-47ce1a00-e612-11e9-894e-24671c916bb5.png)

Called by svg.node.js:

![image](https://user-images.githubusercontent.com/2772908/66172710-63392500-e612-11e9-89d8-1376826d8615.png)

**Comment by The-Crocop** [comment]
same issue here

**Comment by The-Crocop** [comment]
All right I figured out the issue. There is a fix pushed into the github repository, which fixes the firstElementChild method. But in npm we stil have the old version. SO your best bet is to download this repository and link locally. Or upload the newest version on master to npm and then use from there.

**Comment by Fuzzyma** [comment]
I bumped the verson and published a new version. This should work now.
