### ISSUE TITLE
<style> support?

### ISSUE THREAD

**Issue by nornagon** [svgdotjs/svgdom#51]
Hey there! I'm using svgdom to extract SVG path data to be [used as input](https://github.com/nornagon/saxi) to a [pen plotter](https://www.axidraw.com/). I'd like to use stroke color information to separate layers so that, for example, I can lay down all the red paths with one pen, then switch pens, and lay down all the blue paths with a different pen.

Currently I'm able to extract stroke color data correctly if it's specified either as a `stroke="#f00"` attribute or a `style="stroke: #f00"` attribute, but svgdom doesn't seem to parse css that's present in a `<style>` tag.

Is this something you'd consider supporting?

**Comment by Fuzzyma** [comment]
No, unfortunately this is not possible. Css is not interpreted at all. We only deal with the dom itself and support some visual functions like getBBox(), getBoundingClientRect(), getCTM() and getScreenCTM(). This methods also only use information available from the dom and ignore any styles.
