### ISSUE TITLE
core-js 2 is no longer supported

### ISSUE THREAD

**Issue by jwatte** [svgdotjs/svgdom#57]
When installing svgdom, NPM complains that core-js version 2.6 is no longer supported, and core-js version 3 or higher should be used.
That being said -- do you need core-js at all? (Also -- 98 packages? really? It would probably be cheaper to emit SVG using just string concatenation...)

**Comment by Fuzzyma** [comment]
I dont use core-js. Must be one of the dependencies.

> Also -- 98 packages? really? It would probably be cheaper to emit SVG using just string concatenation...

Feel free to write a font file parser on your own. Oh - and an xml parser, too. Ah, what I am talking about - just write your own dom implementation with zero dependencies. I am kidding - but I guess you got the point ;)

**Comment by michael-brade** [comment]
> I dont use core-js. Must be one of the dependencies.

yup. It is `fontkit`, which still uses `babel-runtime` version 6.x instead of `@babel/runtime` (version 7.x), and babel 6 depends on the old `core-js`. So you might turn to `fontkit`.
