### ISSUE TITLE
A method to clean the canvas?

### ISSUE THREAD

**Issue by kadaliao** [svgdotjs/svgdom#6]
HI, I'm creating a service to generate svg on the server. 

I have to delete require.cache[require.resolve('svgdom')] to get a clean canvas every time.

It would be great if there is a function that like canvas.clear() to do so.

Thanks.

**Comment by Fuzzyma** [comment]
Are you using svg.js? If so just do `canvas.clear()`.
I am planning on exporting a factory function instead of an instance for window. That would solve your problem. However, I am not sure when I will find the time to do that

**Comment by kadaliao** [comment]
@Fuzzyma Thanks for the reply. 

I just tried canvas.clear() using svg.js, and it works.

Cheers.
