### ISSUE TITLE
{svg.js GROUP}.svg() throw "Error: Doctype can only be appended to document"

### ISSUE THREAD

**Issue by MichinariNukazawa** [svgdotjs/svgdom#61]
Can't success running svg.js method `svg()`.
The code that worked before the update was broken.

I update svgdom.
```
-    "svgdom": "0.0.21",
+    "svgdom": "0.1.4",
```
(use svg.js version is `     "svg.js": "^2.7.1",`)

call: `group_edge_icon.svg(rendering_handle.resource.edge_icon_svg);`
(`rendering_handle.resource.edge_icon_svg` is raw svg string from read svg file.)

throw this error.
`Error: Doctype can only be appended to document`

====

console.log(rendering_handle.resource.edge_icon_svg)
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="レイヤー_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
	 y="0px" width="32px" height="32px" viewBox="0 0 32 32" enable-background="new 0 0 32 32" xml:space="preserve">
<line fill="#FFFFFF" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-miterlimit="10" x1="30" y1="2" x2="2" y2="30"/>
<line fill="#FFFFFF" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-miterlimit="10" x1="30" y1="12" x2="12" y2="30"/>
<line fill="#FFFFFF" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-miterlimit="10" x1="30" y1="22" x2="22" y2="30"/>
</svg>
```

throw call graph
```
/home/nuka/daisy_sequence/daisy_sequence/node_modules/svgdom/main-require.cjs:1879
      throw new Error('Doctype can only be appended to document')
      ^

Error: Doctype can only be appended to document
    at SAXParser.HTMLParser.parser.ondoctype (/home/nuka/daisy_sequence/daisy_sequence/node_modules/svgdom/main-require.cjs:1879:13)
    at emit (/home/nuka/daisy_sequence/daisy_sequence/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/nuka/daisy_sequence/daisy_sequence/node_modules/sax/lib/sax.js:629:5)
    at SAXParser.write (/home/nuka/daisy_sequence/daisy_sequence/node_modules/sax/lib/sax.js:1132:13)
    at HTMLParser (/home/nuka/daisy_sequence/daisy_sequence/node_modules/svgdom/main-require.cjs:1929:10)
    at HTMLElement.set (/home/nuka/daisy_sequence/daisy_sequence/node_modules/svgdom/main-require.cjs:933:77)
    at initializer.svg (/home/nuka/daisy_sequence/daisy_sequence/node_modules/svg.js/dist/svg.js:1247:24)
    at Function.draw_fragment (/home/nuka/daisy_sequence/daisy_sequence/js/renderer.js:718:21)
    at Function.rendering_ (/home/nuka/daisy_sequence/daisy_sequence/js/renderer.js:262:14)
    at Function.get_dummy_draw_from_diagram_ (/home/nuka/daisy_sequence/daisy_sequence/js/daisy-io.js:104:12)
```

**Comment by Fuzzyma** [comment]
So first of all, this lib is still in the 0.x.x versions so every release can possibly break something,
Especially when there is a jump from 0.0.x to 0.x. With this in mind: Did you fix the obvious things like how you connect the library with svg.js? 

If so: Are you trying to append a whole svg file to a group? Does this file has a doctype in it? The doctype was former skipped when parsing but isnt anymore. That means, it potentially tries to append a doctype to a group. So the error might be just correct.

However it is not great user experiecen. I just wonder now if it is possible to allow this kind of operation without breaking spec compliance (not that this lib is very much spec compliant lol)

**Comment by MichinariNukazawa** [comment]
Thanks for your reply.
I already fixed other problem with svg.js version change.
/** daisy_sequence (my app) release package differs from the sample due to other document export issues.
```
    - const canvas = SVG(document.documentElement)
    + const canvas = SVG(document.createElementNS('http://www.w3.org/2000/svg','svg'))
```
However, this issue confirmation uses `document.documentElement` according to the sample code.
*/

I tryed remove DOCTYPE line from source svg file.
Disappear error, but distination svg group is empty.
`				<g id="SvgjsG1373" class="fragment__edge-icon"></g>`
I changed the svg tag to group in source svg file , but the result is the same.

**Comment by Fuzzyma** [comment]
The correct way should be look somehow like this:

```js
const { createSVGWindow } = require('svgdom')
const window = createSVGWindow
const SVG = require('svg.js')(window)

const canvas = SVG(document.documentElement)
```

About the other exporting issues: You might want to consider svg.js v3. The export method was reworked and should work far more reliable now.

**Comment by MichinariNukazawa** [comment]
Deleting the DOCTYPE solved the this problem.
Sorry, ".svg() import empty" is my test code bug. (target watch file is not updated.)

I try svg.js v3 update. thanks.
