### ISSUE TITLE
0.1.x breaks style.setProperty

### ISSUE THREAD

**Issue by michael-brade** [svgdotjs/svgdom#62]
Hi,

I just tried to upgrade to the shiny new svgdom 0.1.4. But it breaks `Element.style.setProperty()`:  https://github.com/svgdotjs/svgdom/blob/053219ee2ca71fea076ce24fcc9a26d398145688/src/dom/Element.js#L28 

This line, for some reason, invokes the Proxy getter again, which then returns a string, which then errors with e.g.
```
TypeError: Cannot create property '--size' on string ''
```

**Comment by michael-brade** [comment]
Doh! Of course this invokes the getter: `this.style[...]` is a getter of `style` on `this`, and only then the array/object property is accessed and written. I don't know the syntax to invoke the setter here... :open_mouth:

**Comment by Fuzzyma** [comment]
Nice. Thank you!
