### ISSUE TITLE
attribute names becoming lowercase when setting innerHTML

### ISSUE THREAD

**Issue by ikoruk** [svgdotjs/svgdom#64]
When setting innerHTML explicitly from string with camelcase attributes, the dom transforms all its attributes to lowercase. This breaks elements like `viewBox` that need to be in camel case to work.

**Comment by Fuzzyma** [comment]
Goot catch. Will look into it. Do you have a bit of example code for me?

**Comment by ikoruk** [comment]
```
const template = document.createElement('template');
template.innerHTML = `<svg viewBox="0 0 100 100"></svg>`;
console.log(template.innerHTML);
```
returns
```
<svg viewbox="0 0 100 100"></svg>
````

**Comment by Fuzzyma** [comment]
I already see the problem. Atm, innerHTML gets parsed in the namespace the parent element is in. Since the template tag is in HTML namespace (and there is no cdata section), it parses its content as html. And html doesnt now different cases (its all uppercase). Not sure how to fix it beside from adding an exception for the template element so that it doesnt get parsed as html (doesnt feel right)

**Comment by Fuzzyma** [comment]
Atually there might be an easy solution. Just put an xmlns attribute on the svg with the svg namespace and that should solve it

**Comment by Fuzzyma** [comment]
To be fair: I cannot even find the code were this conversion happens. I skimmed to the whole codebase. I never cast the attribute to lowercase. Only the tagname...

**Comment by ikoruk** [comment]
About xmlns, it happens anyway with it:
```
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 100 100"></svg>
```

And it also happens if I set my window to a xml namespace with:
```
const window = createWindow('"http://www.w3.org/2000/svg', 'svg');
```
or `createSVGWindow`

For example:
```
document.documentElement.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>`;
console.log(document.documentElement.outerHTML);
```
with `createSVGWindow`, no `template` tag at all returns:
```
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 100 100"></svg>
```

**Comment by Fuzzyma** [comment]
ok. Thank you for investigating. Might be a problem with the sax parser then. I will take a deeper look!

**Comment by Fuzzyma** [comment]
lol forget to fix it in the named commit - so reopen
