### ISSUE TITLE
Issue parsing transform matrix with leading space (easy fix!)

### ISSUE THREAD

**Issue by killroy42** [svgdotjs/svgdom#66]
I just encountered an issue where I didn't get correct bounding boxes (they had null and NaN values).

I tracked it down to this piece of SVG: `transform="matrix( 1, 0, 0, 1, 0,0) "`
Changing it to this makes it work: `transform="matrix(1, 0, 0, 1, 0, 0) "`

It got messed up by the leading space, since the regexes aren't very clean. But there is a simple fix:

In the file `node.js` in the `matrixify` function, line 272 change the following:
from: `kv[1].split(regex.delimiter)`
to: `kv[1].trim().split(regex.delimiter)`

A more "correct" solution likely would be to check if we should delimit by commas or spaces, and regex accordingly.

**Comment by Fuzzyma** [comment]
actually the delimiter consumes spaces and commas so that is already working - but yeah - guess we forgot to trim there :D.
I am still wondering if it might be faster to actually parse that value instead of all this regex magic...
Thanks for the headsup. Will fix it

**Comment by killroy42** [comment]
Yeah, I guess a leading/trailing space will result in extra null values in the array. I'd recommend either a nice regexp for the entire matrix, or a proper parser in general.

**Comment by Fuzzyma** [comment]
Just realised: You seem to be using an old version because that file doesnt exist anymore :D. However - the bug still exists and I just fixed it on my side. Thank you!
