### ISSUE TITLE
The library is relying on global window/document state

### ISSUE THREAD

**Issue by Rush** [svgdotjs/svgdom#70]
Hello,
I was considering your library on the server to process/generate some SVG in a dynamic way, unfortunately it looks like your code has this global function `registerWindow` as shown here https://github.com/svgdotjs/svgdom#get-started-with-svgjs-v3x

Looks like svg.js v2.x (x>5) example is actually more helpful to running on the server

**Comment by Fuzzyma** [comment]
No, v3 of svg.js is far better off being used on the server-side. What makes you think it isn't?
`registerWindow` is not a global function. It is imported from the svg.js package
