### ISSUE TITLE
Does getComputedStyle do anything?

### ISSUE THREAD

**Issue by hegelstad** [svgdotjs/svgdom#81]
Referring to this function:

https://github.com/svgdotjs/svgdom/blob/13083d30945a9c0c0faca37c1b172d3a6c413ce7/src/dom/Window.js#L42-L64

Does it do anything except from returning a function which it does not call?

**Comment by Fuzzyma** [comment]
If you need a complete rendering engine, yes! Svgdom just gives you Dom. It will not calculate styles or render anything. For that you need an actual browser
