### ISSUE TITLE
Default Font Not Being Overridden

### ISSUE THREAD

**Issue by calvinsomething** [svgdotjs/svgdom#90]
I followed the Readme for setting the font like so:

```
const window = createSVGWindow()
registerWindow(window, window.document)

const canvas = SVG(window.document.documentElement) as Container

config
	.setFontDir(`${fontDir}`)
	.setFontFamilyMappings({"Jersey M54": "Jersey M54.ttf"})

canvas.text("TESTING").font("family", "Jersey M54")
```

The text works except for the font. I get this error:

> Could not open font "sans-serif" in file "/fontDir/OpenSans-Regular.ttf". Error: ENOENT: no such file or directory, open '/fontDir/OpenSans-Regular.ttf'

I've tried using `.preloadFonts()` as well as `.font({family: "Jersey M54")`. I've also tried setting the `config` properties both before creating and right before registering the window. It's really hard to know what's going wrong because there's not really any documentation and the other Github issue that is similar to this is from an older version of the library.

**Comment by Fuzzyma** [comment]
Yoi create a text element and set the font afterwards. So it first tries to use the default font which it can't find in the font folder. That's why it throws

**Comment by calvinsomething** [comment]
Great, thank you. The error is gone but the font is still not working. I will look into it further and see what's going wrong (the fonts are working for the node-canvas package, so I think the files should be fine).

**Comment by calvinsomething** [comment]
When calling the `canvas.font("family")` getter, the correct font family is set.. but it appears OpenSans-Regular is being used. Any idea how this could be happening?
