### ISSUE TITLE
Can this run without Node.Js in an embedded Javascript VM

### ISSUE THREAD

**Issue by kariem2k** [svgdotjs/svgdom#93]
It is a great idea and makes great things possible.

I was wondering if I could use svgdom and svg.js in an embedded JVM like duktape (without having node.js)? 

Thanks

**Comment by Fuzzyma** [comment]
This lib relies on node libraries so unless you find a replacement for every used dependency and adapt the api access, this won't be possible.

**Comment by kariem2k** [comment]
Thanks for your quick answer
